### ISSUE TITLE
CORS Paper mode issue?

### ISSUE THREAD

**Issue by dimitri-deychak** [117/alpaca#101]
**Description**
CORS policy error when using API on Paper mode

**Expected**
Works as normal

**Reproduction**
Steps we can take to reproduce the bug:
1. Use `paper: true` and add paper keys to constructor 

**Logs**
![Screen Shot 2022-04-02 at 5 52 54 PM](https://user-images.githubusercontent.com/85982195/161403971-13c23ace-e0c7-459f-9975-6d5de28afad8.png)

**Additional**
Am I doing something wrong here? I am developing my system and want to utilize the paper account for testing runs. But I am not able to use any features since I am getting this CORS policy - I don't get it when using non-paper mode.

**Comment by 117** [comment]
In your fetch have you tried adding `mode: 'no-cors',`?

**Comment by 117** [comment]
You may need to bypass CORS for your localhost application with an extension like https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/.

**Comment by 117** [comment]
This is not the case if you run it without the browser.

**Comment by dimitri-deychak** [comment]
Thanks, makes sense.

**Comment by Manas-Nagelia** [comment]
In production, how will we prevent the CORS error? And in development, are you saying to use the browser extension to bypass the error?
