### ISSUE TITLE
Add unit tests for parser

### ISSUE THREAD

**Issue by lbstr** [117/alpaca#17]
There are other areas that could be tested too, but I feel like the parser is a good start.

**Comment by 117** [comment]
Which of these do you prefer?

- https://jestjs.io/ (has mocking built in)
- https://github.com/avajs/ava

**Comment by lbstr** [comment]
Jest. I've never used ava, but I do have a ton of experience with Jest.

**Comment by 117** [comment]
Jest it is then, I've been wanting to use it. 😄

**Comment by lbstr** [comment]
OK awesome! I should be able to get it set up. The part where I struggled with AVA was getting tsc to ignore the test files, so hopefully I can figure that out second time around.

**Comment by KalebMills** [comment]
Will there be a separate lib used for assertions, or will just the `assert` package be used?

**Comment by 117** [comment]
Really thorough man, loving these additions. 😄
