### ISSUE TITLE
Wrong typings

### ISSUE THREAD

**Issue by yovanoc** [117/alpaca#21]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/7302317/97617012-8c96d100-1a1d-11eb-995a-2640933104e7.png">

For the `getBars` method, this is not a Map, because TS won't let us doing a `bars[symbol]` thing,  he wants to use the Map .get method... so we have to force TS with a `as` like that otherwise we have an any type:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/7302317/97617196-c7990480-1a1d-11eb-89cd-3ab929b38459.png">

**Comment by 117** [comment]
Thanks for reporting this issue, fixed in this [commit](https://github.com/117/alpaca/commit/2ed108f61c740302f56bc70b1ecaf1b63fb36563). 🙂
