### ISSUE TITLE
NodeError: Must use import to load ES Module

### ISSUE THREAD

**Issue by ehab180hb** [117/alpaca#22]
So the code doesn't work, since the it build into "ESNEXT" according to https://github.com/117/alpaca/blob/master/tsconfig.json
You're using the `export from` syntax which is not supported by the latest version of node yet.

Try it here: https://runkit.com/ehab180hb/5f9f225f041987001aafe129

**Comment by 117** [comment]
I have this fixed in the latest version [v2.1.3](https://www.npmjs.com/package/@master-chief/alpaca/v/2.1.3). Let me know if this resolves the issue. 🙂

**Comment by ehab180hb** [comment]
Works like a charm, thanks!
