### ISSUE TITLE
Types for streams

### ISSUE THREAD

**Issue by KalebMills** [117/alpaca#26]
Looks like [here](https://github.com/117/alpaca/blob/main/src/stream.ts#L104) a generic emitter is used when something is received over the socket connection. This bit of code looks handy, but it's not useful as it pertains to types. Seems since this is supposed to be a Typescript superset of the alpacas library, these should be individually typed. 

My suggestion is to add overloads the allow types to be had for these emitted values.

**Comment by 117** [comment]
Will write them later today. They should be typed in the first place 🤦‍♂️. Good issue! 🙂

**Comment by KalebMills** [comment]
[PR](https://github.com/117/alpaca/pull/27)
