### ISSUE TITLE
Browser build

### ISSUE THREAD

**Issue by husayt** [117/alpaca#42]
**Is your feature request related to a problem? Please describe.**
Currently library only runs on server side, It can't be run in browser.

**Describe the solution you'd like**
I don't see a reason this library couldn't work in browser. For instance, instead of node-fetch we could just use fetch in browser. 
Instead of `ws` we could use [isomorphic-ws](https://github.com/heineiuo/isomorphic-ws)
Same goes for other dependencies.

**Additional context**
instead of node-fetch  we could also use [ky-universal](https://github.com/sindresorhus/ky-universal).

**Comment by 117** [comment]
I'm in full agreement the changes should be made 🙂. I'll begin the transition on the staging branch.

**Comment by 117** [comment]
This improvement would also enable Deno users to import and use this library.

**Comment by husayt** [comment]
> I'm in full agreement the changes should be made 🙂. I'll begin the transition on the staging branch.

That would't be necessary, here is a pull request #43 which does it. In addition to above mentioned libraries I also replaced `limiter` with `bottleneck.` I tested it works fine in browser. Would be nice also to add an example and do a browser only bundle. Since I work with ESM directly, there was no need for me. But might be a good thing to add. I guess will need `rollup` or smth similar to produce bundle

**Comment by 117** [comment]
Merged.

**Comment by 117** [comment]
We need to make sure it supports both common js and es imports.

**Comment by husayt** [comment]
@117 see #44 please

**Comment by 117** [comment]
After some testing I will be publishing 4.0.0 to NPM. Great work!
