### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by husayt** [117/alpaca#47]
**Description**
@117 when I merged latest commits, build got broken for me.

I don't see anything which could have broken the build in those commits.  Maybe something changed on my side? Could you please try `npm run build` on your side?

**Comment by 117** [comment]
It builds just fine for me. What about the build is broken on your end?

**Comment by husayt** [comment]
I have spent four hours tryin to get it build and now it just works. I suspect update in some dependency due to imminent typescript 4.2 release. Whatever it was, is fixed now. Thanks for double checking. I have found problems with sockets and will be releasing a fix shortly
