### ISSUE TITLE
A more streamlined API.

### ISSUE THREAD

**Issue by AqilCont** [117/alpaca#5]
Client.getAsset(), Client.getAssets(), Client.getWatchlist(), Client.createWatchlist(), etc. seems like a really outdated way to do a modern API. I would suggest an `Client.assets` property that has an assets cache and the required methods built-in like this:
```ts
Client.assets.get(parameters?: GetAssetsParameters): Promise<Asset|Asset[]> {
    return this.request(method.GET, BaseURL.Account, parameters.asset_id_or_symbol ? "assets/" + parameters.asset_id_or_symbol : "assets?" + qs.stringify(parameters));
}
```
which gets all assets without parameters and specific assets using given parameters otherwise. This can be done with watchlists, account configurations, clocks, calendars, and many other methods/objects.

**Comment by AqilCont** [comment]
Also, camelCase is super outdated xd

**Comment by 117** [comment]
> Also, camelCase is super outdated xd

I'm ex-Java it's second nature to me.. :(

**Comment by AqilCont** [comment]
Ohhh, I have a few friends who also retain Java practices when starting javascript. I am telling you, it will make you end up in a deep, unescapable hole of regret in many projects as these two languages are extremely different and you need a fresh mind for both.

**Comment by AqilCont** [comment]
Also, after learning JavaScript and mainly TypeScript practices, I can never look at Java code without frustration or disgust anymore.

**Comment by 117** [comment]
> Also, after learning JavaScript and mainly TypeScript practices, I can never look at Java code without frustration or disgust anymore.

Java is for dinosaurs.

**Comment by 117** [comment]
Also adding on to your initial suggestion... could you explain a bit more what you mean by assets cache? Because assets and some of their fields may change minute by minute, a cache of them wouldn't be all that helpful in that sense.

**Comment by AqilCont** [comment]
Ohhh, I am a bit new at the stock market and some people just asked me to try making a bot. I found out Alpaca like 2 days ago and now I'm here xd

**Comment by 117** [comment]
Welcome to the Alpaca community! :) You ok with me closing this issue or is there more you'd like to add for streamlining the package?

**Comment by AqilCont** [comment]
Oh yeah, two things:
- Caching in relatively static things, with changes immediately applied on websocket events and such.
- Better Events API pls.

**Comment by AqilCont** [comment]
Also, I wanted to push something else but keep getting this error:
![image](https://user-images.githubusercontent.com/32044067/86535440-5ea9e180-beae-11ea-8964-19a0424324f3.png)

**Comment by AqilCont** [comment]
I usually only have private repos on personal projects so I'm not used to pushing much, and would love some help xd.

**Comment by AqilCont** [comment]
If there's some permission problem, I can just send the file over.

**Comment by 117** [comment]
> Also, I wanted to push something else but keep getting this error(I didn't feel like opening an issue because this is probably me being extremely dumb):
> ![image](https://user-images.githubusercontent.com/32044067/86535440-5ea9e180-beae-11ea-8964-19a0424324f3.png)

No one can push directly to repo except for owners or collaborators. If you wish to make changes you must first fork the repo to your own account, commit changes there, then submit a pull request.

**Comment by AqilCont** [comment]
I'm too lazy so can you just commit this yourself?
Here is a completely redone README.md. You have the code, so you can revise and change whatever you want before committing too:

# alpaca-trade-api-ts

![Version](https://img.shields.io/github/package-json/v/117/alpaca-trade-api-ts?color=196DFF&style=flat-square)
![Language](https://img.shields.io/github/languages/code-size/117/alpaca-trade-api-ts?color=F1A42E&style=flat-square)
![Maintenance](https://img.shields.io/maintenance/yes/2020?style=flat-square)
![Prettier(idk)](https://img.shields.io/static/v1?label=code%20style&message=prettier&color=ff51bc&style=flat-square)

A TypeScript Node.js library for the <https://alpaca.markets> REST API and
WebSocket streams.

**Table of Contents:**

- [alpaca-trade-api-ts](#alpaca-trade-api-ts)
  - [Installation](#installation)
  - [`alpaca.Client`](#alpacaclient)
    - [`Client` Initialization](#client-initialization)
    - [Methods](#methods)
      - [isAuthenticated](#isauthenticated)
      - [getAccount](#getaccount)
      - [getOrder](#getorder)
      - [getOrders](#getorders)
      - [placeOrder](#placeorder)
      - [replaceOrder](#replaceorder)
      - [cancelOrder](#cancelorder)
      - [cancelOrders](#cancelorders)
  - [Stream](#stream)
    - [`alpaca.Stream` Initialization](#alpacastream-initialization)
  - [BaseURL](#baseurl)
  - [Contribute](#contribute)

## Installation

```cmd
> npm i 117/alpaca-trade-api-ts
```

## `alpaca.Client`

A client for handling all account based requests.

### `Client` Initialization

The standard way to initialize 

```typescript
// Import the Client
import { Client } from 'alpaca-trade-api-ts'

// The actual initialization
const client = new Client({
  key: '...',
  secret: '...',
  paper: true,
  rate_limit: true,
})
```

You can also use environment variables which will be applied to every new
client.

```cmd
> set APCA_API_KEY_ID=yourKeyGoesHere
> set APCA_API_SECRET_KEY=yourKeyGoesHere
> set APCA_PAPER=true
```

Due to the asynchronous nature of the client we recommended you listen for
interrupts.

```typescript
// Allow pending promises to resolve before exiting the process.
process.on('SIGINT', async () => {

  // Properly closes the client.
  await alpacaClient.close()

  // Then exits the process
  process.exit(0)
})
```

### Methods

All Client instance methods.

#### isAuthenticated

Checks if the client is authenticated.

```typescript
await client.isAuthenticated()
```

#### getAccount

Connects to an Alpaca account.

```typescript
await client.getAccount()
```

#### getOrder

Gets a specific order.

```typescript
await client.getOrder({
  order_id: '6187635d-04e5-485b-8a94-7ce398b2b81c',
})
```

#### getOrders

Gets all orders made by the client.

```typescript
await client.getOrders({
  limit: 25,
  status: 'all',
})
```

#### placeOrder

Places an order using your account.

```typescript
await client.placeOrder({
  symbol: 'SPY',
  qty: 1,
  side: 'buy',
  type: 'market',
  time_in_force: 'day',
})
```

#### replaceOrder

Re-places an order(to change some details maybe).

```typescript
await client.replaceOrder({
  order_id: '69a3db8b-cc63-44da-a26a-e3cca9490308',
  limit_price: 9.74,
})
```

#### cancelOrder

Cancels an order.

```typescript
await client.cancelOrder({
  order_id: '69a3db8b-cc63-44da-a26a-e3cca9490308',
})
```

#### cancelOrders

Cancels every single order(be sure to not make a typo here!)

```typescript
await client.cancelOrders()
```

> More examples are coming soon... give me some time or feel free to contribute.

## Stream

An Alpaca websocket API for streamlining the exchange of requests and data to and from the Alpaca servers.

### `alpaca.Stream` Initialization

An API key is allowed 1 simultaneous connection to each server. Connecting to them is easy:

```typescript
// Imports the Alpaca websocket stream API
import { Stream, BaseURL } from 'alpaca-trade-api-ts';

// Creates a websocket stream
const stream = new Stream(client, {
  host: BaseURL.MarketDataStream,
});

// To see all stream messages use .onMessage
stream.subscribe(['T.SPY']);

// Will get called on each new trade event for SPY
stream.onTrade((trade) => {
  console.log(trade)
});
```

## BaseURL

Contains 2 properties used for securing a connection to an Alpaca websocket:

| URL                                | Enum                       |
| :--------------------------------- | :------------------------- |
| `wss://api.alpaca.markets/stream`  | `BaseURL.AccountStream`    |
| `wss://data.alpaca.markets/stream` | `BaseURL.MarketDataStream` |

## Contribute

Pull requests are encouraged. 😁

**Comment by AqilCont** [comment]
Oh you should add a some of the returns of the functions at the end. This code was so loosely written that it wouldn't have helped much anyways until a more thorough documentation of the returned classes comes out.

**Comment by 117** [comment]
That readme looks great!

**Comment by AqilCont** [comment]
Thanks!! :D

**Comment by AqilCont** [comment]
uh can you extract the raw code from it? I don't know if you completely can. I can properly push the file if you can't.

**Comment by AqilCont** [comment]
Also, I know you are a Java person so you used IntelliJ iDEA a lot before, but Visual Studio Code is a lot better suited for Javascript and Node.js in general for me. Maybe try it out someday :D

**Comment by AqilCont** [comment]
Also, can you link the direct website resources and API responses from the official Alpaca website? It would be helpful.

**Comment by AqilCont** [comment]
Also, uh you don't have any descriptions filled out in the script files themselves, which are also sort of needed if you really want this to be complete. I'm imagining a giant "docs" phase of development now xd.

**Comment by AqilCont** [comment]
I usually just make the docs as I go in my projects.

**Comment by 117** [comment]
> Also, can you link the direct website resources and API responses from the official Alpaca website? It would be helpful.

[https://alpaca.markets/docs/api-documentation/api-v2/account/](https://alpaca.markets/docs/api-documentation/api-v2/account/)

**Comment by AqilCont** [comment]
No, I meant in the API itself lmao.

**Comment by AqilCont** [comment]
Actually, I guess it would be super unnecessary to implement it for every class. I think you should just finally add returned types and classes and it should be awesome.

**Comment by 117** [comment]
> No, I meant in the docs itself lmao.

Ah yeah thats a good idea.

**Comment by AqilCont** [comment]
ok so i commit a lot of things in a new pull request

**Comment by AqilCont** [comment]
uhhh is it possible for you to accept my friend request and talk on Discord? I sent one a bit ago but you never responded...

**Comment by AqilCont** [comment]
I want to discuss further plans there, since GitHub isn't the best place for it.
