### ISSUE TITLE
CancelAll doesn't return as expected

### ISSUE THREAD

**Issue by husayt** [117/alpaca#58]
**Description**
Data passed by CancelAll is not being returned by call

**Reproduction**
Call cancelAll()

![image](https://user-images.githubusercontent.com/1169324/108579448-c9653b80-731e-11eb-8dda-6d5b62f0a9a2.png)

**Logs**
If applicable, add logs to help explain the bug.

**Additional**

**Comment by 117** [comment]
Good find!

**Comment by husayt** [comment]
I actually added this as a reminder for myself to fix, but you did it before I could even start. Thanks @117
