### ISSUE TITLE
Alpaca data api v1 is to be deprecated from 28th of Feb

### ISSUE THREAD

**Issue by husayt** [117/alpaca#60]
Hi, 
we are using v1 for market data, seems that we need to switch to v2.

https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v1/

**Comment by 117** [comment]
I have the historical Alpaca Data v2 code ready, not streaming yet. I'll create a branch for 5.0.0 major version.

**Comment by 117** [comment]
Working on the streaming right now.

**Comment by 117** [comment]
It differs vastly from the scheme of the alpaca account data... should we have a different `Stream` class for both `market_data` and `account` streams?

**Comment by 117** [comment]
I added parsing of dates in 68ab66b78ea11224716ebfe9764a2d25153eccf9.

**Comment by 117** [comment]
Almost done with WebSocket.

**Comment by 117** [comment]
Appears ready, I've marked it as a pre-release and won't be pushing to NPM until I've verified it's functionality on Monday.
