### ISSUE TITLE
LastQuote and other missing methods from v1

### ISSUE THREAD

**Issue by husayt** [117/alpaca#64]
There is no LastQuote method in v2. It seems v1 is still operational. Perhaps we could still use missing methods from v1?

**Comment by husayt** [comment]
@117 I just double checked using old version of  this library and v1 is still working. In this case it is best to keep v1 methods, especially those for which there is no alternative in v2

**Comment by 117** [comment]
I agree it should be.

**Comment by husayt** [comment]
From what I heard `last_quote` and `last_trade` methods are planned to be added to v2 at some point, until then at least v1 versions will be available.

**Comment by 117** [comment]
I'm on it.

**Comment by 117** [comment]
The included methods in version `6.0.0+` are:

- `getBars_v1`
- `getLastQuote`
- `getLastTrade`

**Comment by ColtonIdle** [comment]
Does getLastQuote rely on v1? If so, should that be in the method name as well like you did for getBars?

**Comment by 117** [comment]
> Does getLastQuote rely on v1? If so, should that be in the method name as well like you did for getBars?

Hmm, it probably should be if Alpaca intends to add these methods to v2 as well.
