### ISSUE TITLE
Consider adding a CHANGELOG

### ISSUE THREAD

**Issue by eikeon** [117/alpaca#65]
**Is your feature request related to a problem? Please describe.**

Knowing what's changed in new releases.

Consider adding a CHANGELOG

**Describe the solution you'd like**

Perhaps something like https://github.com/conventional-changelog/standard-version to generate it. It's pretty quick and easy to set up and use. 

**Describe alternatives you've considered**

Generating it by hand; but wouldn't recommend this option.

**Additional context**

Think it's definitely worth the small effort to set up and will pay that investment back quickly.

**Comment by 117** [comment]
Added in 44a578ccee9745f7f2f725915557292cadcdd2ad. Thank you for the suggestion, going forward i'll make sure that's kept up to date.
