### ISSUE TITLE
Fails to build in nodejs environment

### ISSUE THREAD

**Issue by FredrikNoren** [117/alpaca#66]
Hi! I'm trying to use this library with firebase functions (node 12 environment), but I'm getting a build error from `tsc`.

It's a newly create firebase functions project (so fairly standard settings). This is my tsconfig file:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "typeRoots": ["node_modules/@types"]
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

This is the output:
```

node_modules/@master-chief/alpaca/@types/stream.d.ts:1:23 - error TS2688: Cannot find type definition file for 'ws'.

1 /// <reference types="ws" />
                        ~~

node_modules/@master-chief/alpaca/@types/stream.d.ts:2:8 - error TS1259: Module '"/Users/fredrik/github/garagefunds/functions/node_modules/isomorphic-ws/index"' can only be default-imported using the 'esModuleInterop' flag

2 import WebSocket from 'isomorphic-ws';
         ~~~~~~~~~

  node_modules/isomorphic-ws/index.d.ts:8:1
    8 export = WebSocket
      ~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/@master-chief/alpaca/@types/stream.d.ts:3:8 - error TS1259: Module '"/Users/fredrik/github/garagefunds/functions/node_modules/eventemitter3/index"' can only be default-imported using the 'esModuleInterop' flag

3 import EventEmitter from 'eventemitter3';
         ~~~~~~~~~~~~

  node_modules/eventemitter3/index.d.ts:134:1
    134 export = EventEmitter;
        ~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/isomorphic-ws/index.d.ts:6:28 - error TS7016: Could not find a declaration file for module 'ws'. '/Users/fredrik/github/garagefunds/functions/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm install @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

6 import WebSocket = require('ws')
                             ~~~~


Found 4 errors.
```

Any idea what this might be about?

**Comment by husayt** [comment]
Why don't you try node14, it is supported in firebase.

**Comment by FredrikNoren** [comment]
@husayt I just tried changing "engine" in package.json to 14, and I'm also running 15 locally, but still getting the same error as above. This error also happens in the typescript compile step so think it shouldn't matter at that point? (Though could be wrong)

**Comment by 117** [comment]
Try removing `typeRoots` from the `compilerOptions`.

**Comment by FredrikNoren** [comment]
@117 That gave me a whole lot more errors; it's probably because this project is in a subfolder of another project (that's the default way firebase projects are set up; the "app" as the root project and then the firebase functions in a subfolder of that). I think the typeRoots are there to make sure it's not using the parents typeRoots

**Comment by husayt** [comment]
@FredrikNoren ok, that narrows the problem . Can you try adding esModuleInterop flag to your ts config?

**Comment by FredrikNoren** [comment]
@husayt Hm yeah when I do that it removes the stream and eventemitter3 error (though some others appear, but they're related to my code and I can probably fix them). But the `Cannot find type definition file for 'ws'.` remains

**Comment by 117** [comment]
Looking into a fix.

**Comment by 117** [comment]
Try installing the types for ws? `npm i --save @types/ws`

**Comment by husayt** [comment]
@117 I don't think there is something to fix on our side. I have a typescript project which works just fine. It has to be smth with they way project configured.

Here is a sample tsconfig, which works for me:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "ESNext",
    "target": "es2016",
    "lib": ["DOM", "ESNext"],
    "strict": true,
    "esModuleInterop": true,
    "incremental": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
  },
  "exclude": ["node_modules"]
}
```

**Comment by FredrikNoren** [comment]
@117 Doh, yeah installing ws types solved it! Should have tried it but I just assumed they were already included. Thanks!
