### ISSUE TITLE
Cannot use compiled package with jest due to ESM errors

### ISSUE THREAD

**Issue by neeschit** [117/alpaca#69]
**Description**
Running into ESM related error trying to use the package with jest

**Expected**
Package should work with jest on node v14. My suspicion is something isn't transpiled correctly?

**Reproduction**
Example repo that reproduces the error:
https://github.com/neeschit/alpaca-jest-issue

**Logs**
```
 Details:

    /Users/nranganath/playground/alpaca-jest-test/node_modules/@master-chief/alpaca/dist/mjs/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { AlpacaClient } from './client.js';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { AlpacaClient } from "@master-chief/alpaca";
        | ^
      2 |
      3 | export const client = new AlpacaClient({
      4 |     credentials: {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (index.ts:1:1)
      
```

<img width="1169" alt="Screen Shot 2021-05-09 at 1 08 18 AM" src="https://user-images.githubusercontent.com/8795953/117561261-28efff00-b063-11eb-8cf0-36bb04e0c52f.png">

**Additional**
I've tried using `transformIgnorePatterns` as specified [here](https://github.com/kulshekhar/ts-jest/issues/970), but no luck

FYI, I can get it to run just fine with node directly, just jest that's a problem

**Comment by neeschit** [comment]
I spent quite a while trying to figure out where the breakage is, but I'm totally stumped right now

**Comment by 117** [comment]
When I have free time I'm going to keep looking into resolving this.

**Comment by 117** [comment]
Apologies, still haven't had time to circle back to this.

**Comment by kevindra** [comment]
I also started getting this #77 . It's a bummer as it's failing all other tests when I use this library.
I tried Jest's config to include library.. but didn't help..
```js
module.exports = {
  ...
  transformIgnorePatterns: ["<rootDir>/node_modules/(?!@master-chief/alpaca)"],
};

```

**Comment by 117** [comment]
@kevindra I've done some research into it across other related issues on GitHub, could not find a way to get it behaving nicely across the board. Open to ideas though.

**Comment by kevindra** [comment]
Thanks! I've switched to mocha and sinon now. No issues there. Spend few hours fixing this issue but couldn't so had to make this call. 🙂

**Comment by reessm01** [comment]
Hello, I am experiencing this as well. <insert grumbling here/>

I want to keep this issue fresh as this is a great solution I hope not to have to depart from! 

I have not yet come up with anything, but I'll report back if I do.  I've got some old projects on a retired machine that might have some answers. We shall see...

**Comment by 117** [comment]
> Hello, I am experiencing this as well. <insert grumbling here/>
> 
> 
> 
> I want to keep this issue fresh as this is a great solution I hope not to have to depart from! 
> 
> 
> 
> I have not yet come up with anything, but I'll report back if I do.  I've got some old projects on a retired machine that might have some answers. We shall see...

It's a tough one, any help appreciated 🙏.

**Comment by reessm01** [comment]
No luck. 

In the meantime, I am using jest's __mocks__ for the library, which is good for my needs (primarily boundary testing). I normally achieve that via spies and forget about it.

I am admittedly perplexed by this issue. It may be something I circle back to, but I've got my own problems to solve and need to keep at it. I'll stay tuned though.

Thanks for the prompt replies and attention!

**Comment by 117** [comment]
I totally get it, same situation here. I've spent hours digging to solve it and it's still an enigma.

**Comment by calvintwr** [comment]
I think it has to do with the CommonJS and ES6 module issues.

Jest is trying to transpile the mjs files but not able to do it correctly. We were able to fix this by directing Jest to use the cjs files:

try this in your jest.config.js:

```js
    moduleNameMapper: {
        '@master-chief/alpaca': '<rootDir>/node_modules/@master-chief/alpaca/dist/cjs/index.cjs',
    },
```

**Comment by calvintwr** [comment]
@117 hey nico much thanks. It's very nice of you to credit. If I may could you help to credit @wailinkyaww as well? We found the solution together.

P.S However the underlying issue is not really resolved, but I guess we can go with this. I met similar problems with my repos. I just ditched the whole cjs and mjs altogether, and output a commonJS distro that is compatible with both require and import interfaces:

https://github.com/calvintwr/not/commit/6ce195d09b224f2211b4c6f62c8851abfae3930d

**Comment by 117** [comment]
> @117 hey nico much thanks. It's very nice of you to credit. If I may could you help to credit @wailinkyaww as well? We found the solution together.
> 
> P.S However the underlying issue is not really resolved, but I guess we can go with this. I met similar problems with my repos. I just ditched the whole cjs and mjs altogether, and output a commonJS distro that is compatible with both require and import interfaces:
> 
> [calvintwr/not@6ce195d](https://github.com/calvintwr/not/commit/6ce195d09b224f2211b4c6f62c8851abfae3930d)

Added. This issue has been an enigma to me for months! Thank you both, I'm glad we have at least a client-side solution to direct people to now. :)
