### ISSUE TITLE
PUT requests don't work

### ISSUE THREAD

**Issue by seanmetrix** [117/alpaca#70]
**Description**
PUT requests appear to be broken.

Trying to use client.updateWatchlist complains about a malformed request.

It looks like there is a conditional in the request method that needs to be updated

CURRENT: if (params.method != 'POST' && params.method != 'PATCH') {
CHANGE TO: if (!['POST','PATCH','PUT'].includes(params.method)) {

**Expected**

The watchlist should get updated properly.

**Reproduction**
Steps we can take to reproduce the bug:

Just try using client.updateWatchlist and it will generate an error from the server due to a malformed request.

**Logs**
If applicable, add logs to help explain the bug.

**Additional**

**Comment by 117** [comment]
Thank you for finding the issue.
