### ISSUE TITLE
Does the streaming API still work?

### ISSUE THREAD

**Issue by awweather** [117/alpaca#73]
I've followed the docs on your main github page, but my subscriptions to quotes/updates/etc doesn't work.  I receive a successful authentication message, but when I try to subscribe for quotes, I never get any notifications.

The docs on alpaca's site it shows something like this, but I don't see anything related to subscribing for updates.
```json
{
    "action": "listen",
    "data": {
        "streams": ["trade_updates"]
    }
}
```
But in your example, the action is "subscribe" and the data doesn't appear to be formatted in a similar format.  I'm not sure what I'm missing..

Here is my code for connecting to the socket
```javascript
this.socketConnection.once("authenticated", () => {
      this.socketConnection.subscribe("quotes", ["AAPL, FB, SPY"]);

      this.socketConnection.on("quote", (quote) => {
        console.log(quote);
      });

      this.socketConnection.on("bar", (bar) => {
        console.log(bar);
      });

      this.socketConnection.on("trade", (trade) => {
        console.log(trade);
      });

      this.socketConnection.on("trade_updates", (update) => {
        console.log(update);
      });
});`

**Comment by 117** [comment]
If you try:
```javascript 
stream.on('message', (data) => console.log(data))
```
Do you receive the desired subscription messages?

**Comment by 117** [comment]
The following code is working for me locally:

```javascript
import { AlpacaStream } from '@master-chief/alpaca'

const stream = new AlpacaStream({
  credentials: {
    key: 'mykey',
    secret: 'mysecret',
  },
  type: 'account',
  source: 'iex',
})

stream.once('authenticated', () => stream.subscribe('trade_updates'))
stream.on('trade_updates', (data) => console.log(data))
```

Results in:

```console
{
  event: 'canceled',
  execution_id: '2a206db5-4e27-4e74-b5cf-61394e4c036c',
  ...
}
```

**Comment by awweather** [comment]
The code below produces these 3 messages in my console:
{ T: 'success', msg: 'connected' }
{ T: 'success', msg: 'authenticated' }
{ T: 'error', code: 400, msg: 'invalid syntax' }

`new AlpacaStream({
        credentials: {
          key: process.env.ALPACA_API_KEY_PAPER,
          secret: process.env.ALPACA_SECRET_KEY_PAPER,
          paper: true,
        },
        type: "account",
        source: "iex"
      }),`


` this.socketConnection.on("message", (data) => {
      console.log(data);
    });

    this.socketConnection.on("quote", (quote) => {
      console.log(quote);
    });

    this.socketConnection.on("bar", (bar) => {
      console.log(bar);
    });

    this.socketConnection.on("trade", (trade) => {
      console.log(trade);
    });

    this.socketConnection.on("trade_updates", (update) => {
      console.log(update);
    });

    this.socketConnection.once("authenticated", () => {
      this.socketConnection.subscribe("quotes", ["AAPL, FB, SPY"]);
    });`

**Comment by 117** [comment]
In your socket connection you pass the array of quotes as one string:

```ts 
["AAPL, FB, SPY"]
```

This is incorrect they should be individual strings:

```ts
["AAPL", "FB", "SPY"]
```

It is also important that you switch the `type` to `market_data` in the `AlpacaStream` constructor. If quotes is what you wish to receive, the example below works for me:

```ts
const stream = new AlpacaStream({
  credentials: {
    key: 'myKey',
    secret: 'mySecret',
  },
  type: 'market_data',
})

stream.once('authenticated', () =>
  stream.subscribe('quotes', ['AAPL', 'FB', 'SPY']),
)

stream.on('subscription', ({ quotes }) =>
  console.log(`subscribed to ${quotes.join(',')}`),
)

stream.on('quote', (quote) => console.log(quote))
```

I get the following output when running the above code:

```text
subscribed to SPY,AAPL,FB
```
Hope this ends up working for you. 😃

**Comment by awweather** [comment]
Wow, I'm not sure how I missed the quotes needing to be individual strings.  That seemed to be the issue.  I did have market_data, just showed you the wrong one in the example.  Thanks for taking the time to help with this!  This library has been really helpful
