### ISSUE TITLE
Project looks awesome

### ISSUE THREAD

**Issue by brotzky** [117/alpaca#74]
Hey, I was looking through this project and it's really solid. 
I lead engineering at [Fey](https://feyapp.com) and we're looking for engineers. Wondering if you'd be interested?
Regardless, awesome project. Thanks for maintaining it.

**Comment by 117** [comment]
Thank you for the kind words. After taking a look at Fey, and seeing a lot of similarities with the things I already work on and interest me, I'd love to learn more.

**Comment by brotzky** [comment]
Shoot me an email to dennis@narative.co I can tell you more about the role, our team, ambitions, tech stack.
