### ISSUE TITLE
Upcoming breaking API change

### ISSUE THREAD

**Issue by ccnixon** [117/alpaca#78]
Hello! This is not an issue per se and more a heads up that on September 9th, Alpaca will be implementing a breaking change to the API. 

The change affects "unpriceable" assets, specifically, positions in an account that are not priceable. This can occur when certain corporate actions are processed or when a stock gets delisted. In this scenario, API endpoints that call functions that use asset prices are returning an error response.

In order to avoid the error response and keep the API available even in the event that one of your positions’ underlying asset is missing a price, Alpaca will introduce a minor breaking change to the API.

Starting on September 9, 2021, the following API response fields will change from non-nullable to nullable. They will appear null in the response in the case that the underlying asset is missing the price for some reason.

![image](https://user-images.githubusercontent.com/12958606/131369841-1dd7453d-fa43-4095-8c08-d277891265ce.png)

Additionally, the following API response fields’ values will exclude the account’s position in the unpriceable asset.

![image](https://user-images.githubusercontent.com/12958606/131369907-35582c57-d2ee-4a44-8519-bf66551238dc.png)

Thanks so much for your work building and maintaining this excellent SDK! Please let me know if there are any questions the Alpaca team can help answer in regards to these changes.

**Comment by 117** [comment]
On it, thank you for the notification @ccnixon!
