### ISSUE TITLE
[Question]: Pagination

### ISSUE THREAD

**Issue by dimitri-deychak** [117/alpaca#79]
Can you add documentation on how to continue resolving requests that contain a `next_page_token`?

**Comment by 117** [comment]
Yeah when I have free time this week.

**Comment by dimitri-deychak** [comment]
Thanks. I was able to infer it from Alpaca docs, but still could be useful for others.

**Comment by 117** [comment]
I added pagination examples to the 3 historical methods, thank you for the PR and happy trading! :)
