### ISSUE TITLE
Uncaught (in promise) Error: PageOfTrades parsing failed "Cannot read property 'map' of null"

### ISSUE THREAD

**Issue by UchihaVeha** [117/alpaca#81]
Response `quotes` or `trades` possibility to be null;

Response:
```
{"quotes":null,"symbol":"PALT","next_page_token":null}
```
https://github.com/117/alpaca/blob/b7ff7b5c489df24cd60b2942968a2f97bfefdfae/src/parse.ts#L273

![Screenshot from 2021-10-01 14-37-52](https://user-images.githubusercontent.com/3177055/135614318-b94e150a-5eea-4b91-ad0f-71241c340ef8.png)

**Comment by 117** [comment]
So Alpaca is returning null instead of an empty array?... strange.

**Comment by 117** [comment]
Resolved for Quotes, Trades and Bars in version `^6.3.6`.
