### ISSUE TITLE
Error:  export 'AlpacaClient' (imported as 'AlpacaClient') was not found in '@master-chief/alpaca' (possible exports: default)

### ISSUE THREAD

**Issue by UchihaVeha** [117/alpaca#83]
I am using alpaca in web with `"react-scripts": "^5.0.0-next.37"` and typescript. After update Alpaca from `6.3.2` to `6.3.5` I got this error
```
Error:  export 'AlpacaClient' (imported as 'AlpacaClient') was not found in '@master-chief/alpaca' (possible exports: default)
```
The latest work version from me is: `6.3.4`

**Comment by 117** [comment]
Oops. Reverting removal of `.js` imports.

**Comment by 117** [comment]
Try `6.3.6`, thank you for reporting this quickly.
