### ISSUE TITLE
Add Functionality to Close AlpacaStream?

### ISSUE THREAD

**Issue by tclare** [117/alpaca#94]
Hi there @117! 👋 firstly: fantastic job with this. I've started with Alpaca recently and being able to integrate with Typescript is a lifesaver 🙂 great work!

In building out a strategy for my specific use case, I have recently started thinking about integrating the stream feature. For cleanup purposes, I, as a user of this package would like control over when to close [the underlying Websocket](https://github.com/117/alpaca/blob/main/src/stream.ts#L78), so that I can control when to exit the calling process. Am I missing somewhere this is already built in? Or how would you feel about incorporating a feature like this? Something like `AlpacaStream.close()`?

Would be happy to take point on this also! Thanks for reading 🚀

**Comment by 117** [comment]
Yea maybe expose the entire connection instead, like `.getConnection()` and close from there. Offers a bit more freedom.

**Comment by tclare** [comment]
Sure thing, will make a PR today or tomorrow!
