### ISSUE TITLE
Build Output Not Reflecting Recent PR

### ISSUE THREAD

**Issue by tclare** [117/alpaca#99]
**Description**
Hey there! 🙂 Would you mind running the build output again to incorporate my most recent change (parsing the trade updates stream?) I don't think the `.d.ts` files are in sync with the most recent change. Led to a bug I caught recently where the code was sending a parsed form (`TradeUpdate`) to the handler but the old types were still in effect, `TradeUpdate` really referred to what is now known as a `RawTradeUpdate`. If you're low on time I can even do it, I can also open a PR tonight on the diff from running `npm run build` on the most recent version of master.

**Expected**
Type declaration files (and thus IDE autocomplete) should sync up with my most recent changes parsing the Trade Update stream.

**Reproduction**
Verify that the latest version of master inside does not have newly created interfaces in it. For instance, the `@types/entities.d.ts` file does not have`TradeUpdateEvent` and `RawTradeUpdate` interfaces, and the `@types/parse.d.ts` file does not have the `trade_update` parser function type.

**Logs**
n/a

**Additional**
n/a

**Comment by 117** [comment]
Oops. Forgot that command. 🙃

**Comment by 117** [comment]
Alright, it's in `6.3.16`.

**Comment by tclare** [comment]
Thanks for the quick attention!
